#!/usr/bin/env bash
# This is a bash Script of Multiple Maneuvers
pid_file = "var/run/myscript.pid"

cleanup(){
	rm "$pid_file"
	exit
}

trap cleanup SIGTERM

echo $$ > "$pid_file"
while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
done
