#!/usr/bin/env bash
# This is the Fizz Buzz Script file

idx=1
while ((idx<101))
do
	if [[ $((idx % 3)) -eq 0 && $((idx % 5)) -eq 0 ]]; then
		echo "FizzBuzz"
	elif [[ $((idx % 3)) -eq 0 ]]; then
		echo "Fizz"
	elif [[ $((idx % 5)) -eq 0 ]]; then
		echo "Buzz"
	else
		echo $idx
	fi
	((idx++))
done
