#!/usr/bin/env bash
# This is a Script that prints best school, 4- badluck and 8 goodluck

idx=1

while ((idx<11))
do
	if ((idx==4))
	then
		echo "bad luck"
	elif ((idx==8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((idx++))
done
