#!/usr/bin/env bash
# This script prints the content of a file and lists them after - For LOOP

for item in *
do
	if [[ -f $item ]]; then
		name=$(echo "$item" | cut -d'-' -f2-)
		echo "- $name"
	fi
done
