#!/usr/bin/env bash
# This is the bash script to check if a file exists and then identify the contents

file="school"

if [ -e $file ]
then
	echo "school file exists"
	if [ -s $file ]
	then
		echo "school file is not empty"
		if [ -f $file ]
		then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
