#!/usr/bin/env bash
# This script prints the content of a file and lists them after - For LOOP

for item in ./*
do
	if [[ -f $item ]]; then
		name="${item##*/}"
		output="${name#*-}"
		echo $output
	fi
done
