#!/usr/bin/env bash
# This script prints the content of a file and lists them after - For LOOP

for item in *
do
	if [[ -f $item ]]; then
		if [[ "$item" == *-* ]]; then
			name=$(echo "$item" | cut -d'-' -f2-)
			echo "$name"
		else
			echo "$item"
		fi
	fi
done
